---
micronaut:
    application:
        name: meetup-users
    server:
        port: 8083
    metrics:
        enabled: true

endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
    beans:
        enabled: true
        sensitive: false

consul:
    client:
        registration:
            enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    
---
        
kafka:
    bootstrap:
        servers: broker:9092
---
postgres:
    reactive:
        client:
            port: 5432
            host: postgres
            database: meetup_users
            user: postgres
            password: test
            # maxSize: 5
tracing:
    zipkin:
        enabled: true
        http:
            url: http://localhost:9411
