---
micronaut:
    application:
        name: meetup-groups
    server:
        port: 8082
---
kafka:
    bootstrap:
        servers: broker:9092
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"